# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.ali_cloud_write_auth_role_request import AliCloudWriteAuthRoleRequest

class TestAliCloudWriteAuthRoleRequest(unittest.TestCase):
    """AliCloudWriteAuthRoleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AliCloudWriteAuthRoleRequest:
        """Test AliCloudWriteAuthRoleRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AliCloudWriteAuthRoleRequest`
        """
        model = AliCloudWriteAuthRoleRequest()
        if include_optional:
            return AliCloudWriteAuthRoleRequest(
                arn = '',
                bound_cidrs = [
                    ''
                    ],
                max_ttl = '',
                period = '',
                policies = [
                    ''
                    ],
                token_bound_cidrs = [
                    ''
                    ],
                token_explicit_max_ttl = '',
                token_max_ttl = '',
                token_no_default_policy = True,
                token_num_uses = 56,
                token_period = '',
                token_policies = [
                    ''
                    ],
                token_ttl = '',
                token_type = 'default-service',
                ttl = ''
            )
        else:
            return AliCloudWriteAuthRoleRequest(
        )
        """

    def testAliCloudWriteAuthRoleRequest(self):
        """Test AliCloudWriteAuthRoleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
