# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.transit_create_key_request import TransitCreateKeyRequest

class TestTransitCreateKeyRequest(unittest.TestCase):
    """TransitCreateKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransitCreateKeyRequest:
        """Test TransitCreateKeyRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransitCreateKeyRequest`
        """
        model = TransitCreateKeyRequest()
        if include_optional:
            return TransitCreateKeyRequest(
                allow_plaintext_backup = True,
                auto_rotate_period = '0',
                context = '',
                convergent_encryption = True,
                derived = True,
                exportable = True,
                key_size = 56,
                managed_key_id = '',
                managed_key_name = '',
                type = 'aes256-gcm96'
            )
        else:
            return TransitCreateKeyRequest(
        )
        """

    def testTransitCreateKeyRequest(self):
        """Test TransitCreateKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
