# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.kv_v2_read_metadata_response import KvV2ReadMetadataResponse

class TestKvV2ReadMetadataResponse(unittest.TestCase):
    """KvV2ReadMetadataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KvV2ReadMetadataResponse:
        """Test KvV2ReadMetadataResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KvV2ReadMetadataResponse`
        """
        model = KvV2ReadMetadataResponse()
        if include_optional:
            return KvV2ReadMetadataResponse(
                cas_required = True,
                created_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                current_version = 56,
                custom_metadata = None,
                delete_version_after = '',
                max_versions = 56,
                oldest_version = 56,
                updated_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                versions = None
            )
        else:
            return KvV2ReadMetadataResponse(
        )
        """

    def testKvV2ReadMetadataResponse(self):
        """Test KvV2ReadMetadataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
