# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.google_cloud_generate_static_account_key_request import GoogleCloudGenerateStaticAccountKeyRequest

class TestGoogleCloudGenerateStaticAccountKeyRequest(unittest.TestCase):
    """GoogleCloudGenerateStaticAccountKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleCloudGenerateStaticAccountKeyRequest:
        """Test GoogleCloudGenerateStaticAccountKeyRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleCloudGenerateStaticAccountKeyRequest`
        """
        model = GoogleCloudGenerateStaticAccountKeyRequest()
        if include_optional:
            return GoogleCloudGenerateStaticAccountKeyRequest(
                key_algorithm = 'KEY_ALG_RSA_2048',
                key_type = 'TYPE_GOOGLE_CREDENTIALS_FILE',
                ttl = ''
            )
        else:
            return GoogleCloudGenerateStaticAccountKeyRequest(
        )
        """

    def testGoogleCloudGenerateStaticAccountKeyRequest(self):
        """Test GoogleCloudGenerateStaticAccountKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
