# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.pki_configure_acme_request import PkiConfigureAcmeRequest

class TestPkiConfigureAcmeRequest(unittest.TestCase):
    """PkiConfigureAcmeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PkiConfigureAcmeRequest:
        """Test PkiConfigureAcmeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PkiConfigureAcmeRequest`
        """
        model = PkiConfigureAcmeRequest()
        if include_optional:
            return PkiConfigureAcmeRequest(
                allow_role_ext_key_usage = True,
                allowed_issuers = [
                    ''
                    ],
                allowed_roles = [
                    ''
                    ],
                default_directory_policy = 'sign-verbatim',
                dns_resolver = '',
                eab_policy = 'always-required',
                enabled = True
            )
        else:
            return PkiConfigureAcmeRequest(
        )
        """

    def testPkiConfigureAcmeRequest(self):
        """Test PkiConfigureAcmeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
