# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.app_role_look_up_secret_id_by_accessor_response import AppRoleLookUpSecretIdByAccessorResponse

class TestAppRoleLookUpSecretIdByAccessorResponse(unittest.TestCase):
    """AppRoleLookUpSecretIdByAccessorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppRoleLookUpSecretIdByAccessorResponse:
        """Test AppRoleLookUpSecretIdByAccessorResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppRoleLookUpSecretIdByAccessorResponse`
        """
        model = AppRoleLookUpSecretIdByAccessorResponse()
        if include_optional:
            return AppRoleLookUpSecretIdByAccessorResponse(
                cidr_list = [
                    ''
                    ],
                creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expiration_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                metadata = None,
                secret_id_accessor = '',
                secret_id_num_uses = 56,
                secret_id_ttl = '',
                token_bound_cidrs = [
                    ''
                    ]
            )
        else:
            return AppRoleLookUpSecretIdByAccessorResponse(
        )
        """

    def testAppRoleLookUpSecretIdByAccessorResponse(self):
        """Test AppRoleLookUpSecretIdByAccessorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
