# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.transit_trim_key_request import TransitTrimKeyRequest

class TestTransitTrimKeyRequest(unittest.TestCase):
    """TransitTrimKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransitTrimKeyRequest:
        """Test TransitTrimKeyRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransitTrimKeyRequest`
        """
        model = TransitTrimKeyRequest()
        if include_optional:
            return TransitTrimKeyRequest(
                min_available_version = 56
            )
        else:
            return TransitTrimKeyRequest(
        )
        """

    def testTransitTrimKeyRequest(self):
        """Test TransitTrimKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
