# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.policies_read_acl_policy2_response import PoliciesReadAclPolicy2Response

class TestPoliciesReadAclPolicy2Response(unittest.TestCase):
    """PoliciesReadAclPolicy2Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoliciesReadAclPolicy2Response:
        """Test PoliciesReadAclPolicy2Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PoliciesReadAclPolicy2Response`
        """
        model = PoliciesReadAclPolicy2Response()
        if include_optional:
            return PoliciesReadAclPolicy2Response(
                name = '',
                policy = '',
                rules = ''
            )
        else:
            return PoliciesReadAclPolicy2Response(
        )
        """

    def testPoliciesReadAclPolicy2Response(self):
        """Test PoliciesReadAclPolicy2Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
