# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.leases_renew_lease2_request import LeasesRenewLease2Request

class TestLeasesRenewLease2Request(unittest.TestCase):
    """LeasesRenewLease2Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeasesRenewLease2Request:
        """Test LeasesRenewLease2Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeasesRenewLease2Request`
        """
        model = LeasesRenewLease2Request()
        if include_optional:
            return LeasesRenewLease2Request(
                increment = '',
                lease_id = ''
            )
        else:
            return LeasesRenewLease2Request(
        )
        """

    def testLeasesRenewLease2Request(self):
        """Test LeasesRenewLease2Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
