# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.database_write_role_request import DatabaseWriteRoleRequest

class TestDatabaseWriteRoleRequest(unittest.TestCase):
    """DatabaseWriteRoleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseWriteRoleRequest:
        """Test DatabaseWriteRoleRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseWriteRoleRequest`
        """
        model = DatabaseWriteRoleRequest()
        if include_optional:
            return DatabaseWriteRoleRequest(
                creation_statements = [
                    ''
                    ],
                credential_config = None,
                credential_type = 'password',
                db_name = '',
                default_ttl = '',
                max_ttl = '',
                renew_statements = [
                    ''
                    ],
                revocation_statements = [
                    ''
                    ],
                rollback_statements = [
                    ''
                    ]
            )
        else:
            return DatabaseWriteRoleRequest(
        )
        """

    def testDatabaseWriteRoleRequest(self):
        """Test DatabaseWriteRoleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
