# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.kv_v2_configure_request import KvV2ConfigureRequest

class TestKvV2ConfigureRequest(unittest.TestCase):
    """KvV2ConfigureRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KvV2ConfigureRequest:
        """Test KvV2ConfigureRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KvV2ConfigureRequest`
        """
        model = KvV2ConfigureRequest()
        if include_optional:
            return KvV2ConfigureRequest(
                cas_required = True,
                delete_version_after = '',
                max_versions = 56
            )
        else:
            return KvV2ConfigureRequest(
        )
        """

    def testKvV2ConfigureRequest(self):
        """Test KvV2ConfigureRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
