# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.internal_ui_list_enabled_feature_flags_response import InternalUiListEnabledFeatureFlagsResponse

class TestInternalUiListEnabledFeatureFlagsResponse(unittest.TestCase):
    """InternalUiListEnabledFeatureFlagsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalUiListEnabledFeatureFlagsResponse:
        """Test InternalUiListEnabledFeatureFlagsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalUiListEnabledFeatureFlagsResponse`
        """
        model = InternalUiListEnabledFeatureFlagsResponse()
        if include_optional:
            return InternalUiListEnabledFeatureFlagsResponse(
                feature_flags = [
                    ''
                    ]
            )
        else:
            return InternalUiListEnabledFeatureFlagsResponse(
        )
        """

    def testInternalUiListEnabledFeatureFlagsResponse(self):
        """Test InternalUiListEnabledFeatureFlagsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
