# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.policies_list_acl_policies3_response import PoliciesListAclPolicies3Response

class TestPoliciesListAclPolicies3Response(unittest.TestCase):
    """PoliciesListAclPolicies3Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoliciesListAclPolicies3Response:
        """Test PoliciesListAclPolicies3Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PoliciesListAclPolicies3Response`
        """
        model = PoliciesListAclPolicies3Response()
        if include_optional:
            return PoliciesListAclPolicies3Response(
                keys = [
                    ''
                    ],
                policies = [
                    ''
                    ]
            )
        else:
            return PoliciesListAclPolicies3Response(
        )
        """

    def testPoliciesListAclPolicies3Response(self):
        """Test PoliciesListAclPolicies3Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
