# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.ldap_library_force_check_in_request import LdapLibraryForceCheckInRequest

class TestLdapLibraryForceCheckInRequest(unittest.TestCase):
    """LdapLibraryForceCheckInRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LdapLibraryForceCheckInRequest:
        """Test LdapLibraryForceCheckInRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LdapLibraryForceCheckInRequest`
        """
        model = LdapLibraryForceCheckInRequest()
        if include_optional:
            return LdapLibraryForceCheckInRequest(
                service_account_names = [
                    ''
                    ]
            )
        else:
            return LdapLibraryForceCheckInRequest(
        )
        """

    def testLdapLibraryForceCheckInRequest(self):
        """Test LdapLibraryForceCheckInRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
