# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.aws_configure_client_request import AwsConfigureClientRequest

class TestAwsConfigureClientRequest(unittest.TestCase):
    """AwsConfigureClientRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AwsConfigureClientRequest:
        """Test AwsConfigureClientRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AwsConfigureClientRequest`
        """
        model = AwsConfigureClientRequest()
        if include_optional:
            return AwsConfigureClientRequest(
                access_key = '',
                allowed_sts_header_values = [
                    ''
                    ],
                endpoint = '',
                iam_endpoint = '',
                iam_server_id_header_value = '',
                max_retries = 56,
                secret_key = '',
                sts_endpoint = '',
                sts_region = '',
                use_sts_region_from_client = True
            )
        else:
            return AwsConfigureClientRequest(
        )
        """

    def testAwsConfigureClientRequest(self):
        """Test AwsConfigureClientRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
