# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.jwt_configure_request import JwtConfigureRequest

class TestJwtConfigureRequest(unittest.TestCase):
    """JwtConfigureRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JwtConfigureRequest:
        """Test JwtConfigureRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JwtConfigureRequest`
        """
        model = JwtConfigureRequest()
        if include_optional:
            return JwtConfigureRequest(
                bound_issuer = '',
                default_role = '',
                jwks_ca_pem = '',
                jwks_url = '',
                jwt_supported_algs = [
                    ''
                    ],
                jwt_validation_pubkeys = [
                    ''
                    ],
                namespace_in_state = True,
                oidc_client_id = '',
                oidc_client_secret = '',
                oidc_discovery_ca_pem = '',
                oidc_discovery_url = '',
                oidc_response_mode = '',
                oidc_response_types = [
                    ''
                    ],
                provider_config = None
            )
        else:
            return JwtConfigureRequest(
        )
        """

    def testJwtConfigureRequest(self):
        """Test JwtConfigureRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
