# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.rate_limit_quotas_read_response import RateLimitQuotasReadResponse

class TestRateLimitQuotasReadResponse(unittest.TestCase):
    """RateLimitQuotasReadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RateLimitQuotasReadResponse:
        """Test RateLimitQuotasReadResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RateLimitQuotasReadResponse`
        """
        model = RateLimitQuotasReadResponse()
        if include_optional:
            return RateLimitQuotasReadResponse(
                block_interval = 56,
                inheritable = True,
                interval = 56,
                name = '',
                path = '',
                rate = 1.337,
                role = '',
                type = ''
            )
        else:
            return RateLimitQuotasReadResponse(
        )
        """

    def testRateLimitQuotasReadResponse(self):
        """Test RateLimitQuotasReadResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
