# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.pki_read_crl_configuration_response import PkiReadCrlConfigurationResponse

class TestPkiReadCrlConfigurationResponse(unittest.TestCase):
    """PkiReadCrlConfigurationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PkiReadCrlConfigurationResponse:
        """Test PkiReadCrlConfigurationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PkiReadCrlConfigurationResponse`
        """
        model = PkiReadCrlConfigurationResponse()
        if include_optional:
            return PkiReadCrlConfigurationResponse(
                auto_rebuild = True,
                auto_rebuild_grace_period = '',
                cross_cluster_revocation = True,
                delta_rebuild_interval = '',
                disable = True,
                enable_delta = True,
                expiry = '',
                ocsp_disable = True,
                ocsp_expiry = '',
                unified_crl = True,
                unified_crl_on_existing_paths = True
            )
        else:
            return PkiReadCrlConfigurationResponse(
        )
        """

    def testPkiReadCrlConfigurationResponse(self):
        """Test PkiReadCrlConfigurationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
