# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.aws_configure_identity_integration_request import AwsConfigureIdentityIntegrationRequest

class TestAwsConfigureIdentityIntegrationRequest(unittest.TestCase):
    """AwsConfigureIdentityIntegrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AwsConfigureIdentityIntegrationRequest:
        """Test AwsConfigureIdentityIntegrationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AwsConfigureIdentityIntegrationRequest`
        """
        model = AwsConfigureIdentityIntegrationRequest()
        if include_optional:
            return AwsConfigureIdentityIntegrationRequest(
                ec2_alias = 'instance_id',
                ec2_metadata = [
                    ''
                    ],
                iam_alias = 'unique_id',
                iam_metadata = [
                    ''
                    ]
            )
        else:
            return AwsConfigureIdentityIntegrationRequest(
        )
        """

    def testAwsConfigureIdentityIntegrationRequest(self):
        """Test AwsConfigureIdentityIntegrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
