# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.auth_enable_method_request import AuthEnableMethodRequest

class TestAuthEnableMethodRequest(unittest.TestCase):
    """AuthEnableMethodRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthEnableMethodRequest:
        """Test AuthEnableMethodRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthEnableMethodRequest`
        """
        model = AuthEnableMethodRequest()
        if include_optional:
            return AuthEnableMethodRequest(
                config = None,
                description = '',
                external_entropy_access = True,
                local = True,
                options = None,
                plugin_name = '',
                plugin_version = '',
                seal_wrap = True,
                type = ''
            )
        else:
            return AuthEnableMethodRequest(
        )
        """

    def testAuthEnableMethodRequest(self):
        """Test AuthEnableMethodRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
