# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ahvac.models.entity_batch_delete_request import EntityBatchDeleteRequest

class TestEntityBatchDeleteRequest(unittest.TestCase):
    """EntityBatchDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityBatchDeleteRequest:
        """Test EntityBatchDeleteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityBatchDeleteRequest`
        """
        model = EntityBatchDeleteRequest()
        if include_optional:
            return EntityBatchDeleteRequest(
                entity_ids = [
                    ''
                    ]
            )
        else:
            return EntityBatchDeleteRequest(
        )
        """

    def testEntityBatchDeleteRequest(self):
        """Test EntityBatchDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
