# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

    The version of the OpenAPI document: 1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "ahvac"
VERSION = "1.15.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "aiohttp >= 3.0.0",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="HashiCorp Vault Python async client",
    author="Jacopo Rota",
    author_email="jacopo.r00ta@gmail.com",
    url="https://github.com/r00ta/ahvac",
    keywords=["OpenAPI", "OpenAPI-Generator", "HashiCorp Vault API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache License Version 2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    An async python package to make HTTP calls to Hashcorp vault..
    """,  # noqa: E501
    package_data={"ahvac": ["py.typed"]},
)
